version: '3'

services:


  mysql:
    build: ./db
    image: muse/db:latest
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: muse
      MYSQL_PASSWORD: muse
      MYSQL_DATABASE: muse
